# Generated by Django 4.2.7 on 2023-12-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Date_Published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=255)),
                ('Date_Posted', models.DateField()),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.member')),
            ],
        ),
    ]
